routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {
    //RESOURCES
    Route::resource('admins', 'Admin\\AdminController');
    Route::resource('revendas', 'Admin\\RevendaController');
    Route::resource('bouquets', 'Admin\\BouquetController');
    Route::resource('categories', 'Admin\\CategoryStreamController');
    Route::resource('hosts', 'Admin\\HostStreamController');
    Route::resource('streams', 'Admin\\StreamController');
    Route::resource('movies', 'Admin\\MovieController');
    Route::resource('radios', 'Admin\\RadioController');
    Route::resource('series', 'Admin\\SerieController');
    Route::resource('seasons', 'Admin\\SeasonController');
    Route::resource('episodes', 'Admin\\EpisodeController');

    //DATATABLES
    Route::get('datatable/admins', 'Admin\\AdminController@datatable')->name('admins.datatable');
    Route::get('datatable/revendas', 'Admin\\RevendaController@datatable')->name('revendas.datatable');
    Route::get('datatable/bouquets', 'Admin\\BouquetController@datatable')->name('bouquets.datatable');
    Route::get('datatable/categories', 'Admin\\CategoryStreamController@datatable')->name('categories.datatable');
    Route::get('datatable/hosts', 'Admin\\HostStreamController@datatable')->name('hosts.datatable');
    Route::get('datatable/streams', 'Admin\\StreamController@datatable')->name('streams.datatable');
    Route::get('datatable/movies', 'Admin\\MovieController@datatable')->name('movies.datatable');
    Route::get('datatable/radios', 'Admin\\RadioController@datatable')->name('radios.datatable');
    Route::get('datatable/series', 'Admin\\SerieController@datatable')->name('series.datatable');
    Route::get('datatable/seasons', 'Admin\\SeasonController@datatable')->name('seasons.datatable');
    Route::get('datatable/episodes', 'Admin\\EpisodeController@datatable')->name('episodes.datatable');


    //AUX
    Route::post('password/admins', 'Admin\\AdminController@password')->name('admins.password');
    Route::get('/bouquets/relation/{res}/{uuid}', 'Admin\\BouquetRelationController@index');
    Route::get('/stream/status/{uuid}', 'Admin\\StreamController@status');


});
Route::get('/teste', 'HomeController@teste');
Route::get('/sync', 'Api\\ServiceController@fetch');

resources/views/admin/admins/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="element-wrapper">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <h6 class="element-header">
                        Cadastro de {{ getTitlePage($res) }}
                    </h6>
                </div>
                <div class="col-md-6 text-right">
                    <button onclick="window.history.back();"  class="mr-2 mb-2 btn btn-primary btn-md" type="button">Voltar</button>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="element-box">

                {!! Form::open(['route' => $res.'.store']) !!}

                    @include('admin.'.$res.'.fields')

                    <x-input name="password" text="Senha" placeholder="Digite a Senha" :error="$errors" />

                    <div class="form-group col-sm-12">
                        {!! Form::submit('Salvar', ['class' => 'btn btn-primary']) !!}
                    </div>

                {!! Form::close() !!}
            </div>

        </div>
    </div>

@endsection

resources/views/admin/admins/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="element-wrapper">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <h6 class="element-header">
                        Edição de {{ getTitlePage($res) }}
                    </h6>
                </div>
                <div class="col-md-6 text-right">
                    <button onclick="window.history.back();"  class="mr-2 mb-2 btn btn-primary btn-md" type="button">Voltar</button>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="element-box">
                {!! Form::model($model, ['route' => [$res.'.update', $model->uuid], 'method' => 'patch']) !!}

                @include('admin.'.$res.'.fields')

                <div class="form-group col-sm-12">
                    {!! Form::submit('Salvar', ['class' => 'btn btn-primary']) !!}
                </div>

                {!! Form::close() !!}
            </div>

        </div>
    </div>

@endsection

resources/views/admin/admins/fields.blade.php
<x-input name="name" text="Nome" :value="$model->name ?? ''" placeholder="Digite o Nome" :error="$errors"/>

<x-input name="username" text="Username" :value="$model->username ?? ''" placeholder="Digite o Username" :error="$errors"/>

resources/views/admin/admins/index.blade.php
@extends('layouts.app')

@section('content')
        <div class="element-wrapper">
            <div class="col-md-12">
               <div class="row">
                   <div class="col-md-6">
                       <h6 class="element-header">
                           Gestão de {{getTitlePage($res)}}
                       </h6>
                   </div>
                   <div class="col-md-6 text-right">
                       <a href="{{ route('admins.create') }}" class="mr-2 mb-2 btn btn-primary btn-md" type="button">Cadastrar Usuário</a>
                   </div>
               </div>
            </div>

            <div class="element-box">
                <x-message :message="Session::has('success') ? Session::get('success') : ''"/>

                <div class="table-responsive">
                    {{ csrf_field() }}
                    <table id="users-table" class="table table-striped table-lightfont">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Username</th>
                                <th width="25%">Actions</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
@endsection

@section('scripts')
    @include('admin.admins.js.password')
    @include('admin.common.delete')
@endsection